# Generated by Django 3.2.6 on 2021-08-31 09:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('language', models.CharField(choices=[('ar', 'Arabic'), ('en', 'English')], max_length=10)),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TranslationKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=1024)),
                ('namespace', models.CharField(choices=[('common', 'Common'), ('errors', 'Errors'), ('translation', 'Translation')], max_length=15)),
            ],
        ),
        migrations.AddConstraint(
            model_name='translationkey',
            constraint=models.UniqueConstraint(fields=('name', 'namespace'), name='Translation key'),
        ),
        migrations.AddField(
            model_name='translation',
            name='translation_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translation.translationkey'),
        ),
        migrations.AddConstraint(
            model_name='translation',
            constraint=models.UniqueConstraint(fields=('translation_key', 'language'), name='Translation Value'),
        ),
    ]
